### ISSUE TITLE
[BUG]: Error loading track from YouTube

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/NodeLink#92]
### NodeLink version

[4b68eac](https://github.com/PerformanC/NodeLink/commit/4b68eacc703e5006d59adfd227717e405062e901)

### Description

```js
[search]: Found 5 tracks on SoundCloud for query memories david guetta
[decodetrack]: Received a request from client.
 Params: "/v4/decodetrack"
 Headers: {"accept-encoding":"br, gzip, deflate","user-agent":"FastLink","content-type":"application/json","authorization":"REDACTED","host":"REDACTED","connection":"keep-alive"}
[ALL]: Received a request from client.
 Path: /v4/decodetrack
 Headers: {"accept-encoding":"br, gzip, deflate","user-agent":"FastLink","content-type":"application/json","authorization":"REDACTED","host":"REDACTED","connection":"keep-alive"}
[ALL]: Received a request from client.
 Path: /v4/sessions/j9lI0ajZI1S6JWkV/players/841311038506795008
 Headers: {"accept-encoding":"br, gzip, deflate","user-agent":"FastLink","content-type":"application/json","authorization":"REDACTED","host":"REDACTED","connection":"keep-alive","transfer-encoding":"chunked"}
 Body: "{\"track\":{\"encoded\":\"QAAA5AMAJE1lbW9yaWVzIChmZWF0LiBLaWQgQ3VkaSkgW0V4dGVuZGVkXQAMRGF2aWQgR3VldHRhAAAAAAAAdTAACTI1NjA2ODc1NgABADtodHRwczovL3NvdW5kY2xvdWQuY29tL2RhdmlkZ3VldHRhL21lbW9yaWVzLWZlYXQta2lkLWN1ZGktMQEAN2h0dHBzOi8vaTEuc25kY2RuLmNvbS9hcnR3b3Jrcy1qR3U3MEJVb2cza2gtMC1sYXJnZS5qcGcBAAxGUlpJRDA5MDIxNTAACnNvdW5kY2xvdWQAAAAAAAAAAA==\"}}"
[retrieveStream]: Exception from YouTube for query Memories (feat. Kid Cudi) (Extended): This video is unavailable
[trackEnd]: David Guetta - Memories by Raouf Harzi because it was replaced.
[trackStart]: Memories (feat. Kid Cudi) [Extended] by David Guetta.
file:///home/container/src/utils.js:88
    let req = (url.startsWith('https') ? https : http).request(url, {
                   ^
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///home/container/src/utils.js:88:20
    at new Promise (<anonymous>)
    at http1makeRequest (file:///home/container/src/utils.js:85:10)
    at file:///home/container/src/sources.js:169:116
    at new Promise (<anonymous>)
    at Object.getTrackStream (file:///home/container/src/sources.js:113:10)
    at VoiceConnection.getResource (file:///home/container/src/connection/voiceHandler.js:183:38)
    at VoiceConnection.play (file:///home/container/src/connection/voiceHandler.js:269:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.requestHandler (file:///home/container/src/connection/handler.js:647:16)
Node.js v20.18.0
```

### Client

FastLink ([b70b47d](https://github.com/PerformanC/FastLink/commit/b70b47dd401de86e32e922674602b24e6870bf93))

### Steps to reproduce

Load a track using the youtube source

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1Lucas1apk** [comment]
Error: video arrives as hls without even being a live and the system that resolves it was not working correctly, I even removed it from the codes and I don't know how to fix it, that's why I didn't put it together with the pr, I tried to solve it but I don't know how to use ffmpeg and/or hls decoder

Obs: It actually works with a latency of 5s the video cuts in the middle

**Comment by ThePedroo** [comment]
Please update NodeLink, likely fixed.
