### ISSUE TITLE
[BUG]: its gone shot down

### ISSUE THREAD

**Issue by Limeamirs** [PerformanC/NodeLink#93]
### NodeLink version

v2.3.0

### Description

It just shuts down because of an error. It's rare that it will play music

### Client

byteble

### Steps to reproduce

it turns on, it can play 2-3 tracks, but then it turns off if you play any more

### Example code

NvbS93YXRjaD92PXJFZzc3YWpNYmZNAQCXaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9yRWc3N2FqTWJmTS9ocWRlZmF1bHQuanBnP3NxcD0tb2F5bXdFbUNPQURFT2dDOHF1S3FRTWE4QUVCLUFIYUE0QUM1QUtLQWd3SUFCQUJHRk1nWFNobE1BOD0mcnM9QU9uNENMRGgybXA2ZEVfelZub3h3SXlqN1c0S0F2dWx2dwAAB3lvdXR1YmUAAAAAAAAAAA==","length":269000},"replaceCurrent":false,"volume":100}
file:///root/Nodelink/src/connection/voiceHandler.js:320
    if (this.connection.audioStream)
                        ^

TypeError: Cannot read properties of null (reading 'audioStream')
    at VoiceConnection.volume (file:///root/Nodelink/src/connection/voiceHandler.js:320:25)
    at Server.requestHandler (file:///root/Nodelink/src/connection/handler.js:677:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.1

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Instructions are incomplete, as I cannot repro. Please submit minimal reproducible code and give the steps again

**Comment by Limeamirs** [comment]
After a while of work it crashes with the same error and it has to be turned on again to work.
